### ISSUE TITLE
getList and relatedObjects

### ISSUE THREAD

**Issue by baltrap33** [backand/vanilla-sdk#1]
for a request backand.objects.getList('myObject',{ deep : true, relatedObjects : true})
the response from sdk doesn't contains totalRows and relatedObjects sent by server-side

**Comment by rannn505** [comment]
hey @baltrap33,
You're absolutely right, we will solve this next patch. Thanks for the help. 👍

**Comment by rannn505** [comment]
solved in 1.1.2 version
