### ISSUE TITLE
XMLHttpRequest.DONE

### ISSUE THREAD

**Issue by baltrap33** [backand/vanilla-sdk#2]
I try the angular1-sdk and I don't get response (resolver or reject)
req.onreadystatechange = function () { var _DONE = XMLHttpRequest.DONE || 4; if (req.readyState == _DONE) { var res = _this._createResponse(req, config); if (res.status === 200) { if (config.interceptors.response) { resolve(config.interceptors.response(res)); } else { resolve(res); } } else { if (config.interceptors.responseError) { resolve(config.interceptors.responseError(res)); } else { reject(res); } } } };
_DONE is never 4 but always function
Did i miss something ?

**Comment by rannn505** [comment]
hey @baltrap33 ,
Can you check which number the req.readyState get stuck, please?
And maybe why it get stuck?
What browser are you running?
Have you followed the instructions in angular1-sdk readme?

**Comment by baltrap33** [comment]
Hi @rannn505 , thanks for your help !
I'm using Chrome.
The problem is not about req.readyState, it goes nice to 4 value, 
it's about the condition made and the 'or' value condition : 
 `var _DONE = XMLHttpRequest.DONE || 4;`
in my case : 
`XMLHttpRequest.DONE` always exists but it's always a function, not a value, well with the condition after :
`if (req.readyState == _DONE)` ==> if ( 4 == fn) never works !
Well i never received the responses.
I change the file : 
`if (req.readyState == 4)`
and all works fine now.

Thk U

**Comment by baltrap33** [comment]
I apologize, I try today, and the troubles did'nt appear ;p, well i close the issue.
good job guy
