### ISSUE TITLE
Calling actions doesn't work with GET

### ISSUE THREAD

**Issue by MSCRMGuru** [backand/vanilla-sdk#3]
In services/object.js, lines 73 and 74:
`return utils.http({
    url: `${URLS.objectsAction}/${object}?name=${action}`,
`
We can see the action name appended to the URL with a question mark to signify it is a query string parameter, and then the request is sent to the http util.

In utils/http.js, line 104:
`req.open(config.method, `${config.baseURL ? config.baseURL+'/' : ''}${config.url}${params ? '?'+params : ''}`, true, config.auth.username, config.auth.password);`

This will add the question mark for the parameters, again.

The result is two question marks, and a 404 error from backand server.

The fix would be to change the object.js action get function and add the action to the params object and let the http util handle the rest.  The updated function would look lie :

function get (object, action, params = {}) {
params.name = action;
  return utils.http({
    url: `${URLS.objectsAction}/${object}`,
    method: 'GET',
    params,
  });
}

Have not tested this on POST.

Let me know if more details are needed.

**Comment by baltrap33** [comment]
👍

**Comment by baltrap33** [comment]
same issue for me,
when i used $http() from angular, my action works from backand, but if i used the backand provider
Backand.object.action.get() with params (only with params) , 404 error appears
